version: "3"
services:
  sonarqube:
    build:
      context: .
      dockerfile: Dockerfile.sonarqube
    container_name: reackus-sonarqube
    ports:
      - "19000:9000"
    environment:
      - SONARQUBE_HOME=/opt/sonarqube
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
    networks:
      - reackus_network
  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    container_name: reackus-database
    ports:
      - "13306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=pass
      - MARIADB_DATABASE=reackus
      - MARIADB_USER=user
      - MARIADB_PASSWORD=pass
      - MARIADB_INITDB_SKIP_TZINFO=1
    networks:
      - reackus_network
    volumes:
      - reackus-data:/var/lib/mysql
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 12181:2181
    networks:
      - reackus_network
  kafka:
    image: confluentinc/cp-kafka:7.0.0
    depends_on:
      - zookeeper
    ports:
      - 19092:19092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - reackus_network
  redis:
    image: "redis:6.2.6"
    command: redis-server --requirepass redisPass
    ports:
      - "16379:6379"
    networks:
      - reackus_network
networks:
  reackus_network:
    driver: bridge
volumes:
  reackus-data:
